### PR TITLE
Switch to go-kit/log from go-kit/kit/log

### LINKED ISSUE #17: Switch to gokit/log
Can we switch github.com/go-kit/kit/log => github.com/go-kit/log?

See https://github.com/prometheus/prometheus/issues/9012

### PR DESCRIPTION
**Pull request by LeviHarrison**
We've upgraded in Prometheus to take advantage of the smaller size, causing this package to stop working.

In response to prometheus/prometheus#9012
Fixes #17

### CODE REVIEW

**Comment by LeviHarrison** [comment]
cc @roidelapluie

**Review by bwplotka — APPROVED** [review]

**Comment by roidelapluie** [comment]
Note: this is a breaking change. We might consider moving this as a module in prometheus/common/

**Comment by simonpasquier** [comment]
Thanks!

> Note: this is a breaking change.

IIRC I had to tag it with v2.y.z otherwise the Go toolchain would fail to resolve `github.com/simonpasquier/klog-gokit/v2`.
In theory, I agree that it would have qualify for a major version bump but at the same time, the only usage for this module is to be used inside a replace directive (https://pkg.go.dev/github.com/simonpasquier/klog-gokit/v2?tab=importedby). I think it's fine to tag v2.4.0 and highlight that v2.4.0 (and above) should be used with `github.com/go-kit/log` only. Consumers should mostly know what they're doing but happy to hear opinions.

> We might consider moving this as a module in prometheus/common/

Happy to move it to prometheus/common if you want to.

**Comment by roidelapluie** [comment]
In prometheus/common, we have a module sigv4, which has its own release cycle etc. We could do the same here and go back to a v0.1.0.

**Comment by simonpasquier** [comment]
This is different from the problem that I'm describing. When trying to resolve `github.com/simonpasquier/klog-gokit/v2`, the Go toolchain requires a "v2" tag so you can't have `import github.com/prometheus/common/klog-gokit/v2 v0.1.0`.

```
go: errors parsing go.mod:
go.mod:7:2: require github.com/simonpasquier/klog-gokit/v2: version "v0.3.0" invalid: should be v2, not v0
```
 
See also https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher.

**Comment by simonpasquier** [comment]
Anyway lets merge this and see what we can do even without tagging a new release.

**Comment by roidelapluie** [comment]
Can we do replace k8s.io/klog/v2 => github.com/simonpasquier/klog-gokit/v3 v3.0.0 ?

**Comment by simonpasquier** [comment]
@roidelapluie yes this is the option I was thinking about too. My plan would be that `github.com/simonpasquier/klog-gokit/v3` works only with `github.com/go-kit/log` as a replacement for `k8s.io/klog/v2`. I think we can drop support for `k8s.io/klog`: it isn't used anymore by the kubernetes libraries >= 0.19.x as far as I can see and Prometheus depends on more recent versions. Would it work for you?

The other option would be to create a brand new repository which could be hosted in the prometheus org (or prometheus-community)...

**Comment by bwplotka** [comment]
I think it would good to move to common org, so all team members have control to unblock ourselves (:

**Comment by LeviHarrison** [comment]
Just bringing this up again...

**Comment by simonpasquier** [comment]
My idea is to create a v3 branch (see https://github.com/simonpasquier/klog-gokit/pull/19) that would only support k8s.io/klog/v2 + github.com/go-kit/kit. As an exercise, I've tested it with https://github.com/prometheus-operator/prometheus-operator/pull/4172 and it seems to be working.

**Comment by LeviHarrison** [comment]
Sounds great!

**Pull request merged**
